### ISSUE TITLE
package reaches EOL

### ISSUE THREAD

**Issue by THANOJKUMAR** [steve-community/ocpp-jaxb#1]
Hi,

we are using version 0.0.1 snapshot in our project looks from today we are no more accessible to this maven resources.
Jar version aswell expired on "<Expires>2021-12-29T08:44:51Z</Expires>".

**Comment by goekay** [comment]
hey @THANOJKUMAR sorry for the late reply. the problem should be resolved with [the suggested usage of jitpack](https://github.com/RWTH-i5-IDSG/ocpp-jaxb#how-to-use-it).
